name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: freshkeepuh
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: './package.json'

      - name: Install dependencies
        run: npm ci

      - name: Set up Prisma
        run: npx prisma generate

      - name: Run database migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/freshkeepuh
        run: npx prisma migrate deploy

      - name: Seed the database
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/freshkeepuh
        run: npx prisma db seed

      - name: Build the application
        run: npx next build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/freshkeepuh
        run: npx playwright test --reporter=list
